name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GOTOOLCHAIN: local
    strategy:
      matrix:
        go: [stable] # [ stable, oldstable ]

    steps:

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Get dependencies
      run: go mod download

    - name: Build
      run: go build ./...

    - name: Test
      run: go test ./...

    - name: Lint
      uses: golangci/golangci-lint-action@v7
      with:
        version: latest

    # would be nice, but need to sort the import story
    # - name: Buf
    #   uses: bufbuild/buf-action@v1
    #   with:
    #     pr_comment: false
